version: '3.8'

volumes:
  postgres_data:

networks:
  test_restaurant:
    driver: bridge

services: 
    main:
      container_name: test_restaurant_web
      build: 
        context: .
        dockerfile: Dockerfile
      command: bash -c 'php artisan migrate && php artisan db:seed && php artisan serve --host 0.0.0.0'
      volumes:
        - .:/app
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on: 
        - db
      links:
        - db
      networks:
        - test_restaurant
        
    db:
      image: postgres:13.0-alpine
      restart: 'always'
      container_name: test_restaurant_db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: "${DB_DATABASE}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
      ports:
        - "5434:${DB_PORT}"
      networks:
        - test_restaurant